[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "3.0.0-dev"
edition = "2024"
rust-version = "1.99"
license = "GPL-3.0-or-later"
repository = "https://github.com/nyabi-gh/Ugurugu"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
