# Generated by tools/ts_to_ftl.py from strings.txt and the 2.2.13 catalogues. Do not edit.

# key | Qt context in 2.2.13 | English source [| args=...]
# tools/ts_to_ftl.py turns this into en.ftl, ko.ftl and ja.ftl.

# Menus
menu-file = ファイル
menu-edit = 編集
menu-view = 表示
menu-tools = ツール
menu-window = ウィンドウ
file-new = 新規
file-open = 開く…
file-save = 保存
file-save-as = 名前を付けて保存…
file-export-frame = 現在のフレームを画像で書き出す…
file-quit = 終了
edit-undo = 元に戻す
edit-redo = やり直す
view-zoom-in = 拡大
view-zoom-out = 縮小
view-actual-pixels = 実ピクセル
view-fit = キャンバスを画面に合わせる
view-animate = プレビューを再生
window-animation-bar = アニメーションバーを表示
window-reset-layout = パネル配置をリセット
tool-brush = ブラシ
tool-eraser = 消しゴム
brush-pen = ペン
brush-marker = マーカー
brush-airbrush = エアブラシ
brush-spray = スプレー
ink-pen = インクペン
g-pen = Gペン
round-pen = 丸ペン
monoline = モノライン
bold-ink = 太インク
opaque-marker = 不透明マーカー
transparent-marker = 透明マーカー
highlighter = 蛍光ペン
soft-airbrush = ソフトエアブラシ
hard-airbrush = ハードエアブラシ
dense-airbrush = 濃いエアブラシ
fine-mist = 細かいミスト
pixel-spray = ピクセルスプレー
rough-spray = ラフスプレー
dust-spray = ダストスプレー
droplet-spray = しずくスプレー
wobble-spray = ウォブルスプレー
hard-eraser = ハード
soft-eraser = ソフト
kneaded-eraser = 練り消し
tools-rail = ツール
quick-access = クイックアクセス
panels = パネル
panels-tip = パネルを開く・閉じる

# Status bar and window
status-ready = 準備完了
status-pointer = x { $x }  y { $y }
canvas-zoom = キャンバスのズーム
canvas-zoom-percent = キャンバスのズーム倍率
fit = 全体表示
fit-tip = キャンバス全体をウィンドウに合わせる
untitled = 無題
unsaved-title = 未保存の変更
unsaved-text = ドキュメントに未保存の変更があります。
unsaved-save = 保存(S)
unsaved-discard = 保存しない(N)
unsaved-cancel = キャンセル(ESC)

# Dock title bars
dock-collapse = 折りたたむ
dock-close = パネルを閉じる
dock-expand-area = パレットドックを展開
dock-collapse-area = パレットドックを折りたたむ
dock-handle = { $panel }パネルの移動ハンドル

# Tool settings
tool-settings = ツール設定
size = サイズ
brush-size = ブラシサイズ
eraser-size = 消しゴムサイズ
pen-pressure = 筆圧
pen-pressure-use = タブレットの筆圧を反映
pen-pressure-tip = タブレットの筆圧に応じて線のサイズと不透明度を変えます
stabilization = 手ぶれ補正
stabilization-name = 手ぶれ補正
antialiasing = アンチエイリアス
antialiasing-name = アンチエイリアス
antialiasing-tip = 線の縁を滑らかにします

# Wobble
wobble-dock = ゆらぎ
wobble-whole = 全体
wobble-layer = 編集中のレイヤー
wobble-follow = 全体の設定に従う
wobble-follow-tip = このレイヤーの個別設定を解除し、全体の設定を使用します。
wobble = ウォブル
wobble-scope = ゆらぎの適用先
wobble-preview = ウォブルプレビュー
wobble-preview-tip = 現在のウォブルの強さをリアルタイムで表示します

# Colour
color-dock = 色
color-current = 現在の色

# Layers
layers = レイヤー
layer-add = レイヤーを追加
layer-add-group = 選択したレイヤーを含むグループを追加
layer-ungroup = 選択したグループを解除
layer-merge = 下のレイヤーと結合
layer-delete = レイヤーを削除
layer-up = レイヤーを上へ移動
layer-down = レイヤーを下へ移動
layer-move = レイヤーの移動
merge-select-paint = 結合するペイントレイヤーを選択してください
merge-no-paint-below = 直下にペイントレイヤーがありません
merge-properties = 両方のレイヤーで一致する安全なプロパティが必要で、このレイヤーの上にクリッピングレイヤーがあってはいけません
merge-canvas-change = このレイヤーはキャンバスサイズを変更するか、結合済みの絵を消したことがあるため、結合すると絵が変わります
merge-epoch = レイヤーのキャンバス履歴に互換性がありません
merge-limit = 結合後のレイヤーがストローク数の上限を超えます
blend-mode = ブレンドモード
blend-mode-name = レイヤーのブレンドモード
blend-normal = 通常
blend-multiply = 乗算
blend-screen = スクリーン
blend-overlay = オーバーレイ
percent = { $value }%
opacity = 不透明度
group = グループ
group-parent = 親レイヤーグループ
group-none = グループなし
clip = 下のレイヤーでクリッピング
clip-tip = このレイヤーを下の基準レイヤーの不透明領域内に表示します
reference = 参照レイヤー
reference-tip = マークしたレイヤーを参照する選択ツールでこのレイヤーを使用
layer-visible = レイヤーは表示されています
layer-hidden = レイヤーは非表示です
layer-wobbles = レイヤーはゆらいでいます
layer-still = レイヤーは静止しています
group-fold = グループを折りたたむ
group-unfold = グループを展開

# Animation bar
play-tip = プレビューを再生 (P)
play = プレビューを再生
frame-current = 現在のフレーム
frame-count = アニメーションのフレーム数
fps = FPS
fps-tip = 再生速度（毎秒フレーム数）
fps-name = 再生速度
bar-hide = 折りたたむ
bar-hide-tip = アニメーションバーを折りたたむ (Ctrl+T)
scrubber = フレームスクラバー
scrubber-frame = 全{ $count }フレーム中{ $frame }フレーム目
