# Generated by tools/ts_to_ftl.py from strings.txt and the 2.2.13 catalogues. Do not edit.

# key | Qt context in 2.2.13 | English source [| args=...]
# tools/ts_to_ftl.py turns this into en.ftl, ko.ftl and ja.ftl.

# Menus
menu-file = 파일
menu-edit = 편집
menu-view = 보기
menu-tools = 도구
menu-window = 창
file-new = 새로 만들기
file-open = 열기…
file-save = 저장
file-save-as = 다른 이름으로 저장…
file-export-frame = 현재 프레임을 이미지로 내보내기…
file-quit = 종료
edit-undo = 실행 취소
edit-redo = 다시 실행
view-zoom-in = 확대
view-zoom-out = 축소
view-actual-pixels = 실제 픽셀
view-fit = 캔버스 맞추기
view-animate = 미리보기 재생
window-animation-bar = 애니메이션 바 표시
window-reset-layout = 패널 배치 초기화
tool-brush = 브러시
tool-eraser = 지우개
brush-pen = 펜
brush-marker = 마커
brush-airbrush = 에어브러시
brush-spray = 스프레이
ink-pen = 잉크 펜
g-pen = G펜
round-pen = 둥근 펜
monoline = 모노라인
bold-ink = 굵은 잉크
opaque-marker = 불투명 마커
transparent-marker = 투명 마커
highlighter = 형광펜
soft-airbrush = 부드러운 에어브러시
hard-airbrush = 하드 에어브러시
dense-airbrush = 진한 에어브러시
fine-mist = 미세 분사
pixel-spray = 픽셀 스프레이
rough-spray = 거친 스프레이
dust-spray = 먼지 스프레이
droplet-spray = 물방울 스프레이
wobble-spray = 우글 스프레이
hard-eraser = 딱딱함
soft-eraser = 부드러움
kneaded-eraser = 반죽
tools-rail = 도구
quick-access = 빠른 도구
panels = 패널
panels-tip = 패널 열기 및 닫기

# Status bar and window
status-ready = 준비됨
status-pointer = x { $x }  y { $y }
canvas-zoom = 캔버스 확대/축소
canvas-zoom-percent = 캔버스 확대/축소 배율
fit = 맞춤
fit-tip = 전체 캔버스를 창에 맞추기
untitled = 제목 없음
unsaved-title = 저장되지 않은 변경 사항
unsaved-text = 문서에 저장되지 않은 변경 사항이 있습니다.
unsaved-save = 저장(S)
unsaved-discard = 저장 안 함(N)
unsaved-cancel = 취소(ESC)

# Dock title bars
dock-collapse = 접기
dock-close = 패널 닫기
dock-expand-area = 패널 영역 펼치기
dock-collapse-area = 패널 영역 접기
dock-handle = { $panel } 패널 이동 손잡이

# Tool settings
tool-settings = 도구 설정
size = 크기
brush-size = 브러시 크기
eraser-size = 지우개 크기
pen-pressure = 필압
pen-pressure-use = 필압 반영
pen-pressure-tip = 필압에 따라 선의 크기와 불투명도를 바꿉니다
stabilization = 손떨림 보정
stabilization-name = 손떨림 보정
antialiasing = 안티앨리어싱
antialiasing-name = 안티앨리어싱
antialiasing-tip = 선 가장자리를 부드럽게

# Wobble
wobble-dock = 우글거림
wobble-whole = 전체 그림
wobble-layer = 활성 레이어
wobble-follow = 전체 그림 설정 따르기
wobble-follow-tip = 이 레이어의 개별 설정을 제거하고 전체 그림 설정을 사용합니다.
wobble = 우글거림
wobble-scope = 우글거림 적용 대상
wobble-preview = 우글거림 미리보기
wobble-preview-tip = 현재 우글거림 강도를 실시간으로 보여줍니다
motion-style = 모션 스타일
motion-classic = 클래식
motion-smooth = 부드럽게
motion-stepped = 단계별
motion-poses = 포즈 수
motion-detail = 디테일
motion-linked = 연결
motion-randomness = 무작위성
motion-broken = 끊어진 선
motion-break-amount = 끊김 정도
motion-break-range = 끊김 범위

# Colour
color-dock = 색상
color-current = 현재 색상

# Layers
layers = 레이어
layer-add = 레이어 추가
layer-add-group = 선택한 레이어를 포함하는 그룹 추가
layer-ungroup = 선택한 그룹 해제
layer-merge = 아래 레이어와 병합
layer-delete = 레이어 삭제
layer-up = 레이어 위로 이동
layer-down = 레이어 아래로 이동
layer-move = 레이어 이동
merge-select-paint = 병합할 페인트 레이어를 선택하세요
merge-no-paint-below = 바로 아래에 페인트 레이어가 없습니다
merge-properties = 두 레이어가 동일한 안전 속성을 사용해야 하며, 이 레이어 위에 클리핑 레이어가 없어야 합니다
merge-canvas-change = 이 레이어는 캔버스 크기를 바꾸거나 합쳐진 그림을 지운 적이 있어 병합하면 그림이 달라집니다
merge-epoch = 레이어의 캔버스 기록이 서로 호환되지 않습니다
merge-limit = 병합한 레이어가 선 개수 한도를 초과합니다
blend-mode = 합성 모드
blend-mode-name = 레이어 합성 모드
blend-normal = 일반
blend-multiply = 곱하기
blend-screen = 스크린
blend-overlay = 오버레이
percent = { $value }%
opacity = 불투명도
group = 그룹
group-parent = 상위 레이어 그룹
group-none = 그룹 없음
clip = 아래 레이어에 클리핑
clip-tip = 이 레이어를 아래 기준 레이어의 불투명 영역 안에 표시합니다
reference = 참조 레이어
reference-tip = 표시한 레이어를 참조하는 선택 도구에서 이 레이어 사용
layer-visible = 레이어가 표시되어 있습니다
layer-hidden = 레이어가 숨겨져 있습니다
layer-wobbles = 레이어가 우글거립니다
layer-still = 레이어가 멈춰 있습니다
group-fold = 그룹 접기
group-unfold = 그룹 펼치기

# Animation bar
play-tip = 미리보기 재생 (P)
play = 미리보기 재생
frame-current = 현재 프레임
frame-count = 애니메이션 프레임 수
fps = FPS
fps-tip = 재생 속도 (초당 프레임 수)
fps-name = 재생 속도
bar-hide = 접기
bar-hide-tip = 애니메이션 바 접기 (Ctrl+T)
scrubber = 프레임 스크러버
scrubber-frame = 총 { $count }개 중 { $frame }번째 프레임
