# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Nyabi (nyabi-gh)

"""Writes the Rust app's Fluent files from a list of message keys and the
2.2.13 Qt catalogues, so the 3.0 interface reuses those translations.

Usage: python -X utf8 tools/ts_to_ftl.py

Reads apps/ugurugu/i18n/strings.txt, one message per line:

    key | Qt context | English source [| args=name,name]

The context and source pick the message in i18n/ugurugu_ko.ts and
ugurugu_ja.ts. Qt's %1, %2 become Fluent variables named by `args`, and
mnemonics (&F) are dropped, since the egui menus have none. A message that
2.2.13 does not have uses the context "-" and gives its translations itself:

    key | - | English | 한국어 | 日本語

Then writes apps/ugurugu/i18n/en.ftl, ko.ftl and ja.ftl. It stops on a key
whose message is not in a catalogue rather than leaving it untranslated."""

import os
import re
import sys
import xml.etree.ElementTree as ElementTree

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "apps", "ugurugu", "i18n")


def catalogue(language):
    tree = ElementTree.parse(os.path.join(ROOT, "i18n", f"ugurugu_{language}.ts"))
    messages = {}
    for context in tree.getroot().iter("context"):
        name = context.findtext("name")
        for message in context.iter("message"):
            translation = message.find("translation")
            if translation is None or translation.get("type") in ("unfinished", "vanished", "obsolete"):
                continue
            messages[(name, message.findtext("source"))] = translation.text or ""
    return messages


def plain(text, args):
    text = re.sub(r"\(&\w\)", "", text).replace("&&", "\0").replace("&", "").replace("\0", "&")
    for index, name in enumerate(args, 1):
        text = text.replace(f"%{index}", "\x01" + name + "\x02")
    if "%" in re.sub(r"%%", "", text) and re.search(r"%\d", text):
        raise ValueError(f"unnamed Qt argument in {text!r}")
    return text


def value(text):
    """A Fluent value: braces and leading or trailing spaces quoted."""
    parts = [part for part in re.split(r"(\x01\w+\x02)", text) if part]
    out = []
    for index, part in enumerate(parts):
        if part.startswith("\x01"):
            out.append("{ $" + part[1:-1] + " }")
            continue
        # Fluent drops a value's outer spaces and reads a leading [ * . as
        # syntax, so those and braces are written as string literals.
        edge = (index == 0 and part[0] in " [*.") or (index == len(parts) - 1 and part[-1] == " ")
        if edge or "{" in part or "}" in part:
            out.append('{ "' + part.replace("\\", "\\\\").replace('"', '\\"') + '" }')
        else:
            out.append(part)
    return "".join(out)


def main():
    spec = os.path.join(OUT, "strings.txt")
    catalogues = {language: catalogue(language) for language in ("ko", "ja")}
    files = {"en": [], "ko": [], "ja": []}
    keys = set()
    with open(spec, encoding="utf-8") as lines:
        for number, line in enumerate(lines, 1):
            line = line.rstrip("\n")
            if not line.strip() or line.startswith("#"):
                for language in files:
                    files[language].append(line)
                continue
            fields = [field.strip() for field in line.split("|")]
            key, context, source = fields[0], fields[1], fields[2]
            if key in keys:
                sys.exit(f"strings.txt:{number}: {key} is listed twice")
            keys.add(key)
            args = []
            extra = fields[3:]
            if extra and extra[-1].startswith("args="):
                args = extra.pop()[5:].split(",")
            if context == "-":
                if len(extra) != 2:
                    sys.exit(f"strings.txt:{number}: {key} needs Korean and Japanese text")
                texts = {"en": source, "ko": extra[0], "ja": extra[1]}
            else:
                texts = {"en": source}
                for language, messages in catalogues.items():
                    if (context, source) not in messages:
                        sys.exit(f"strings.txt:{number}: {key}: {context} / {source!r} is not in ugurugu_{language}.ts")
                    texts[language] = messages[(context, source)]
            for language, text in texts.items():
                files[language].append(f"{key} = {value(plain(text, args))}")
    header = "# Generated by tools/ts_to_ftl.py from strings.txt and the 2.2.13 catalogues. Do not edit.\n\n"
    for language, entries in files.items():
        with open(os.path.join(OUT, f"{language}.ftl"), "w", encoding="utf-8", newline="\n") as out:
            out.write(header + "\n".join(entries).strip("\n") + "\n")
    print(f"{len(keys)} messages written")


if __name__ == "__main__":
    main()
